In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import roc_auc_score
import pandas as pd

In [9]:
X = pd.read_csv("data/train.csv")
y = X.pop("profit")

In [10]:
X.describe()

,id,custAge,profession,marital,schooling,default,housing,loan,contact,campaign,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,pmonths,pastEmail,responded
count,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,...,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000
mean,4069.333470,30.095043,4.573126,2.164823,3.496654,0.803223,1.501980,1.132869,1.634576,2.526697,...,0.179571,0.172470,0.063635,93.570722,-40.602854,3.593385,5166.067691,963.810911,0.353544,0.101598
std,2349.013618,19.444441,3.549271,0.612853,2.771274,0.397933,0.542224,0.399008,0.481582,2.717499,...,0.507640,0.453697,1.562797,0.578882,4.641031,1.739818,72.305700,184.155169,1.262559,0.302139
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000,0.000000,0.000000,0.000000
25%,2035.500000,22.000000,1.000000,2.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,-1.800000,93.075000,-42.700000,1.334000,5099.100000,999.000000,0.000000,0.000000
50%,4069.000000,34.000000,3.000000,2.000000,4.000000,1.000000,2.000000,1.000000,2.000000,2.000000,...,0.000000,0.000000,1.100000,93.444000,-41.800000,4.857000,5191.000000,999.000000,0.000000,0.000000
75%,6103.500000,44.000000,8.000000,3.000000,6.000000,1.000000,2.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000,999.000000,0.000000,0.000000
max,8137.000000,94.000000,11.000000,3.000000,7.000000,2.000000,2.000000,2.000000,2.000000,40.000000,...,6.000000,2.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000,999.000000,25.000000,1.000000